version: "3"
services:
  my-postgres:
    build: 
      context: .
      dockerfile: psql.Dockerfile
    ports:
      -  5432:5432
    expose:
      - '5432'
    volumes:
      - '/var/lib/postgresql/data'
  calculator:
    build: 
      context: .
      dockerfile: calc.Dockerfile
    ports:
      -  8080:8080
    expose:
      - '8080'