version: "3"
services:
  postgres:
    image: my-postgres-image:latest
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'history'
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - '/var/lib/postgresql/data'